Console.OutputEncoding = System.Text.Encoding.UTF8;

// ═══ 1. Rich Model ═══
Console.WriteLine("─── 1. Rich Model Round-trip ───");
var cfg = new YamlConfig
{
    Name = "MyApp",
    Version = "2.0.0",
    Port = 8080,
    Pi = 3.14,
    Price = 149.99m,
    CreatedAt = new DateTime(2024, 6, 15, 12, 0, 0, DateTimeKind.Utc),
    ReleaseDate = new DateOnly(2024, 6, 15),
    Id = Guid.Parse("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
    Tags = ["web", "api"],
    Secret = "hidden",
};
var bytes = YamlSerializer.SerializeToUtf8Bytes(cfg);
Console.WriteLine(Encoding.UTF8.GetString(bytes));
var rst = YamlSerializer.Deserialize<YamlConfig>(bytes);
Console.WriteLine($"  OK: {rst?.Name}, Secret: '{rst?.Secret}'");

// ═══ 2. Attributes ═══
Console.WriteLine("\n─── 2. Attributes ───");
Console.WriteLine("  [YamlCamelCase]:");
Console.WriteLine(
    Encoding.UTF8.GetString(
        YamlSerializer.SerializeToUtf8Bytes(new CamelYaml { ProductName = "X", StockCount = 1 })
    )
);

Console.WriteLine("  [YamlKey]+[YamlIgnore]:");
Console.WriteLine(
    Encoding.UTF8.GetString(
        YamlSerializer.SerializeToUtf8Bytes(
            new AttrYaml
            {
                AppName = "Demo",
                Secret = "x",
                Port = 99,
            }
        )
    )
);

Console.WriteLine("  [YamlDateTimeFormat]:");
Console.WriteLine(
    Encoding.UTF8.GetString(
        YamlSerializer.SerializeToUtf8Bytes(new DtYaml { DueDate = new DateTime(2024, 12, 31) })
    )
);

Console.WriteLine("  [YamlConverter]:");
var cb = YamlSerializer.SerializeToUtf8Bytes(new ConvYaml { Tag = new YamlTag { Value = "hi" } });
Console.WriteLine(Encoding.UTF8.GetString(cb));
var cr = YamlSerializer.Deserialize<ConvYaml>(cb);
Console.WriteLine($"  Tag: {cr?.Tag.Value}");

// ═══ 3. Raw Reader ═══
Console.WriteLine("\n─── 3. Raw Reader ───");
var sample = "server:\n  host: localhost\n  port: 8080\n  tags:\n    - web\n    - api\n"u8;
var r = new YamlReader(sample);
while (r.Read())
    Console.WriteLine(
        $"  pos={r.BytesConsumed, 4}  d={r.Depth}  {r.TokenType, -14}  {Encoding.UTF8.GetString(r.KeySpan)}: {Encoding.UTF8.GetString(r.ValueSpan)}"
    );

// ═══ 4. Raw Writer ═══
Console.WriteLine("\n─── 4. Raw Writer ───");
var buf = new ArrayBufferWriter<byte>(256);
var w = new YamlWriter(buf);
w.WriteComment("Generated by PicoYaml");
w.WritePropertyName("server"u8);
w.WriteStartMapping();
w.WritePropertyName("host"u8);
w.WriteString("localhost"u8);
w.WritePropertyName("port"u8);
w.WriteNumber(8080);
w.WriteEndMapping();
w.WritePropertyName("tags"u8);
w.WriteStartMapping();
w.WriteSequenceItem("web"u8);
w.WriteSequenceItem("api"u8);
w.WriteEndMapping();
Console.WriteLine(Encoding.UTF8.GetString(buf.WrittenSpan));

// ═══ 5. IBufferWriter overload ═══
Console.WriteLine("─── 5. Serialize<T>(IBufferWriter) ───");
var pb = new ArrayBufferWriter<byte>(64);
YamlSerializer.Serialize(pb, new YamlConfig { Name = "X" });
Console.WriteLine($"  Bytes: {pb.WrittenSpan.Length}");

// ═══ 6. NaN guard ═══
Console.WriteLine("\n─── 6. NaN Guard ───");
try
{
    new YamlWriter(new ArrayBufferWriter<byte>(64)).WriteDouble(double.NaN);
}
catch (ArgumentException ex)
{
    Console.WriteLine($"  {ex.Message}");
}

// ═══ 6. File I/O — read from data file ═══
Console.WriteLine("\n─── 6. File I/O ───");
var df = Path.Combine(AppContext.BaseDirectory, "data", "config.yaml");
var fb = File.ReadAllBytes(df);
var ff = YamlSerializer.Deserialize<YamlConfig>(fb);
Console.WriteLine($"  Read {df} ({fb.Length} bytes)");
Console.WriteLine($"  Config: {ff?.Name} v{ff?.Version}");
Console.WriteLine($"  Tags: [{string.Join(", ", ff?.Tags ?? [])}]");

var rb = YamlSerializer.SerializeToUtf8Bytes(ff!);
var rr = YamlSerializer.Deserialize<YamlConfig>(rb);
Console.WriteLine($"  Round-trip OK: {rr?.Name == ff?.Name}");

Console.WriteLine("\nAll samples passed.");

// ═══ Models ═══
public class YamlConfig
{
    public string Name { get; set; } = "";
    public string Version { get; set; } = "";
    public int Port { get; set; }
    public double Pi { get; set; }
    public decimal Price { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateOnly ReleaseDate { get; set; }
    public Guid Id { get; set; }
    public List<string> Tags { get; set; } = [];

    [YamlIgnore]
    public string Secret { get; set; } = "";
}

[YamlCamelCase]
public class CamelYaml
{
    public string ProductName { get; set; } = "";
    public int StockCount { get; set; }
}

public class AttrYaml
{
    [YamlKey("app_name")]
    public string AppName { get; set; } = "";

    [YamlIgnore]
    public string Secret { get; set; } = "";

    [YamlKey("listen_port")]
    public int Port { get; set; }
}

public class DtYaml
{
    [YamlDateTimeFormat("yyyy-MM-dd")]
    public DateTime DueDate { get; set; }
}

public class YamlTag
{
    public string Value { get; set; } = "";
}

public class TagCvt : IYamlConverter<YamlTag>
{
    public void Write(IBufferWriter<byte> w, YamlTag v)
    {
        w.Write(Encoding.UTF8.GetBytes($"[{v.Value}]"));
    }

    public YamlTag Read(ref YamlReader r)
    {
        return new YamlTag { Value = Encoding.UTF8.GetString(r.ValueSpan).Trim('[', ']') };
    }
}

public class ConvYaml
{
    [YamlConverter(typeof(TagCvt))]
    public YamlTag Tag { get; set; } = new();
}
