using PicoYaml;

// ═══ Rich Sample: YAML serialization ═══
var config = new AppConfig
{
    Title = "MyApp",
    Version = 2,
    Debug = true,
    Port = 8080,
    Host = "localhost",
    Pi = 3.14
};

// Serialize
var bytes = YamlSerializer.SerializeToUtf8Bytes(config);
Console.WriteLine("=== Serialized YAML ===");
Console.WriteLine(Encoding.UTF8.GetString(bytes));

// Deserialize
var restored = YamlSerializer.Deserialize<AppConfig>(bytes);
Console.WriteLine($"\n=== Round-trip ===");
Console.WriteLine($"  Title:   {restored?.Title}");
Console.WriteLine($"  Version: {restored?.Version}");
Console.WriteLine($"  Debug:   {restored?.Debug}");
Console.WriteLine($"  Port:    {restored?.Port}");
Console.WriteLine($"  Host:    {restored?.Host}");
Console.WriteLine($"  Pi:      {restored?.Pi}");
Console.WriteLine(
    $"  OK: {restored?.Title == config.Title && restored?.Version == config.Version}"
);

// ═══ Low-level Reader demo ═══
Console.WriteLine("\n=== Reader token stream ===");
var raw = "server:\n  host: localhost\n  port: 8080\n  tags:\n    - web\n    - api\n"u8;
var r = new YamlReader(raw);
while (r.Read())
{
    var prefix = r.TokenType switch
    {
        PicoSerDe.Abs.TokenType.ObjectStart => "+ ",
        PicoSerDe.Abs.TokenType.ObjectEnd => "- ",
        PicoSerDe.Abs.TokenType.PropertyName => "  ",
        _ => "? "
    };
    Console.WriteLine(
        $"  {prefix}{r.TokenType, -14} {Encoding.UTF8.GetString(r.KeySpan), -10} {Encoding.UTF8.GetString(r.ValueSpan)}"
    );
}

// ═══ Writer demo ═══
Console.WriteLine("\n=== Writer output ===");
var buf = new ArrayBufferWriter<byte>(256);
var w = new YamlWriter(buf);
w.WriteComment("Generated by PicoYaml");
w.WritePropertyName("app"u8);
w.WriteString("demo"u8);
w.WritePropertyName("server"u8);
w.WriteStartMapping();
w.WritePropertyName("host"u8);
w.WriteString("localhost"u8);
w.WritePropertyName("port"u8);
w.WriteNumber(8080);
w.WriteEndMapping();
w.WritePropertyName("tags"u8);
w.WriteStartMapping();
w.WriteSequenceItem("web"u8);
w.WriteSequenceItem("api"u8);
w.WriteEndMapping();
Console.WriteLine(Encoding.UTF8.GetString(buf.WrittenSpan));

public class AppConfig
{
    public string Title { get; set; } = "";
    public int Version { get; set; }
    public bool Debug { get; set; }
    public int Port { get; set; }
    public string Host { get; set; } = "";
    public double Pi { get; set; }
}
