global using System.Buffers;
global using System.Buffers.Text;
global using System.Collections.Concurrent;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Intrinsics;
global using System.Text;
global using PicoSerDe.Abs;
