Console.OutputEncoding = System.Text.Encoding.UTF8;

// ═══ 1. Sectioned model with nested objects ═══
Console.WriteLine("─── 1. Complex Model ───");
var cfg = new AppConfig
{
    Title = "MyApp",
    Version = 2,
    CreatedAt = DateTime.UtcNow,
    Timeout = TimeSpan.FromSeconds(30),
    Tags = ["web", "api"],
    Server = new ServerCfg { Host = "example.com", Port = 443 },
    Secret = "hidden",
};
var ini = IniSerializer.Serialize(cfg);
Console.WriteLine(ini);
var rst = IniSerializer.Deserialize<AppConfig>(Encoding.UTF8.GetBytes(ini));
Console.WriteLine($"  OK: {rst?.Title}, Secret ignored: '{rst?.Secret}'");

// ═══ 2. Attributes ═══
Console.WriteLine("\n─── 2. Attributes ───");
Console.WriteLine("  [IniCamelCase]:");
Console.WriteLine(IniSerializer.Serialize(new CamelCfg { ProductName = "X", StockCount = 1 }));

Console.WriteLine("  [IniSection]+[IniKey]+[IniIgnore]:");
Console.WriteLine(
    IniSerializer.Serialize(
        new AttrCfg
        {
            AppName = "Demo",
            Secret = "x",
            Port = 99,
        }
    )
);

Console.WriteLine("  [IniDateTimeFormat]:");
Console.WriteLine(IniSerializer.Serialize(new DtCfg { Date = new DateTime(2024, 6, 15) }));

// ═══ 3. Raw Reader ───
Console.WriteLine("\n─── 3. Raw Reader ───");
var r = new IniReader(";config\n[server]\nhost = localhost\nport = 8080\n"u8.ToArray());
while (r.Read())
{
    if (r.TokenType == TokenType.ObjectStart)
        Console.WriteLine($"  Section: {Encoding.UTF8.GetString(r.GetStringRaw())}");
    else if (r.TokenType == TokenType.PropertyName)
    {
        var key = Encoding.UTF8.GetString(r.GetStringRaw());
        r.Read(); // value
        Console.WriteLine($"  {key} = {Encoding.UTF8.GetString(r.GetStringRaw())}");
    }
}

// ═══ 4. Raw Writer ───
Console.WriteLine("\n─── 4. Raw Writer ───");
var buf = new ArrayBufferWriter<byte>(256);
var w = new IniWriter(buf);
w.WriteComment("Generated by PicoIni");
w.WriteSection("app");
w.WriteKeyValue("name", "demo");
w.WriteKeyValue("port", 8080);
Console.WriteLine(Encoding.UTF8.GetString(buf.WrittenSpan));

// ═══ 5. IBufferWriter overload ───
Console.WriteLine("─── 5. Serialize<T>(IBufferWriter) ───");
var pb = new ArrayBufferWriter<byte>(64);
IniSerializer.Serialize(pb, new AppConfig { Title = "X" });
Console.WriteLine($"  Bytes: {pb.WrittenSpan.Length}");

// ═══ 6. File I/O — read from data file ═══
Console.WriteLine("\n─── 6. File I/O ───");
var df = Path.Combine(AppContext.BaseDirectory, "data", "config.ini");
var text = File.ReadAllText(df);
var fb = Encoding.UTF8.GetBytes(text);
var ff = IniSerializer.Deserialize<AppConfig>(fb);
Console.WriteLine($"  Read {df} ({fb.Length} bytes)");
Console.WriteLine($"  Config: {ff?.Title} v{ff?.Version}");
Console.WriteLine($"  Tags: [{string.Join(", ", ff?.Tags ?? [])}]");

var rt = IniSerializer.Serialize(ff!);
var rr = IniSerializer.Deserialize<AppConfig>(Encoding.UTF8.GetBytes(rt));
Console.WriteLine($"  Round-trip OK: {rr?.Title == ff?.Title}");

Console.WriteLine("\nAll samples passed.");

Console.WriteLine("\nAll samples passed.");

public class ServerCfg
{
    public string Host { get; set; } = "";
    public int Port { get; set; }
}

public class AppConfig
{
    public string Title { get; set; } = "";
    public int Version { get; set; }
    public DateTime CreatedAt { get; set; }
    public TimeSpan Timeout { get; set; }
    public List<string> Tags { get; set; } = [];
    public ServerCfg Server { get; set; } = new();

    [IniIgnore]
    public string Secret { get; set; } = "";
}

[IniCamelCase]
public class CamelCfg
{
    public string ProductName { get; set; } = "";
    public int StockCount { get; set; }
}

[IniSection("custom")]
public class AttrCfg
{
    [IniKey("app_name")]
    public string AppName { get; set; } = "";

    [IniIgnore]
    public string Secret { get; set; } = "";

    [IniKey("listen_port")]
    public int Port { get; set; }
}

public class DtCfg
{
    [IniDateTimeFormat("yyyy-MM-dd")]
    public DateTime Date { get; set; }
}
