namespace PicoJson.Gen;

[Generator(LanguageNames.CSharp)]
public sealed class JsonSerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeProviders = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, _) => Transform(ctx)
            )
            .Where(static t => t is not null)
            .Select(static (t, _) => t!.Value);

        context.RegisterSourceOutput(
            typeProviders.Collect(),
            static (spc, types) => GenerateAll(spc, types)
        );
    }

    private static bool IsCandidate(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax { Expression: var expr })
            return false;

        SimpleNameSyntax? name = expr switch
        {
            MemberAccessExpressionSyntax { Name: var n } => n,
            MemberBindingExpressionSyntax { Name: var n } => n,
            _ => null,
        };

        if (name is not GenericNameSyntax { TypeArgumentList.Arguments.Count: 1 } gn)
            return false;

        return gn.Identifier.Text is "Serialize" or "SerializeToUtf8Bytes" or "Deserialize";
    }

    private static TypeInfo? Transform(GeneratorSyntaxContext ctx)
    {
        if (ctx.SemanticModel.GetSymbolInfo(ctx.Node).Symbol is not IMethodSymbol method)
            return null;

        // Must be a method on PicoJson.JsonSerializer
        if (
            method.ContainingType.Name != "JsonSerializer"
            || method.ContainingType.ContainingNamespace?.ToDisplayString() != "PicoJson"
        )
            return null;

        if (method.TypeArguments.Length != 1)
            return null;

        var typeArg = method.TypeArguments[0];

        // Skip built-in / special types
        if (typeArg.SpecialType != SpecialType.None)
            return null;

        if (typeArg is not INamedTypeSymbol namedType)
            return null;

        var ns = namedType.ContainingNamespace?.ToDisplayString() ?? "";
        var properties = new List<PropertyInfo>();

        foreach (var member in namedType.GetMembers())
        {
            if (member is not IPropertySymbol prop)
                continue;
            if (prop.DeclaredAccessibility != Accessibility.Public)
                continue;
            if (prop.IsStatic || prop.IsIndexer)
                continue;
            if (prop.IsReadOnly && prop.SetMethod is null)
                continue;
            if (prop.GetMethod is null)
                continue;

            var typeKind = GetTypeKind(prop.Type);
            if (typeKind is null)
                continue;

            var jsonName = GetJsonPropertyName(prop) ?? prop.Name;
            properties.Add(new PropertyInfo(prop.Name, jsonName, typeKind));
        }

        return new TypeInfo(
            namedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            ns,
            namedType.Name,
            properties.ToArray()
        );
    }

    private static string? GetTypeKind(ITypeSymbol type) =>
        type.SpecialType switch
        {
            SpecialType.System_String => "string",
            SpecialType.System_Int32 => "int32",
            SpecialType.System_Int64 => "int64",
            SpecialType.System_Double => "float64",
            SpecialType.System_Single => "float64",
            SpecialType.System_Boolean => "boolean",
            _ => null,
        };

    private static string? GetJsonPropertyName(IPropertySymbol prop)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (
                attr.AttributeClass?.Name == "JsonPropertyNameAttribute"
                && attr.AttributeClass.ContainingNamespace?.ToDisplayString() == "PicoJson"
                && attr.ConstructorArguments.Length == 1
                && attr.ConstructorArguments[0].Value is string name
            )
                return name;
        }
        return null;
    }

    private static void GenerateAll(SourceProductionContext spc, ImmutableArray<TypeInfo> types)
    {
        var seen = new HashSet<string>();
        foreach (var type in types)
        {
            if (!seen.Add(type.FullyQualifiedName))
                continue;
            var source = GenerateTypeCode(type);
            spc.AddSource(
                $"{type.Name}_JsonSerializer.g.cs",
                SourceText.From(source, Encoding.UTF8)
            );
        }
    }

    private static string GenerateTypeCode(TypeInfo type)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Buffers;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using PicoSerDe.Abs;");
        sb.AppendLine("using PicoJson;");

        if (!string.IsNullOrEmpty(type.Namespace))
        {
            sb.AppendLine();
            sb.Append("namespace ");
            sb.Append(type.Namespace);
            sb.AppendLine(";");
        }

        sb.AppendLine();

        // ---------- Serializer ----------
        AppendSerializer(sb, type);

        sb.AppendLine();

        // ---------- Deserializer ----------
        AppendDeserializer(sb, type);

        sb.AppendLine();

        // ---------- Registration ----------
        AppendRegistration(sb, type);

        return sb.ToString();
    }

    private static void AppendSerializer(StringBuilder sb, TypeInfo type)
    {
        sb.Append("    file readonly struct ");
        sb.Append(type.Name);
        sb.Append("JsonSerializer : ISerializer<");
        sb.Append(type.Name);
        sb.AppendLine(">");
        sb.AppendLine("    {");
        sb.Append("        public void Serialize(IBufferWriter<byte> writer, ");
        sb.Append(type.Name);
        sb.AppendLine(" value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var jw = new JsonWriter(writer);");
        sb.AppendLine("            jw.WriteStartObject();");

        foreach (var prop in type.Properties)
        {
            var u8Name = $"\"{prop.JsonName}\"u8";

            sb.Append("            jw.WritePropertyName(");
            sb.Append(u8Name);
            sb.AppendLine(");");

            switch (prop.TypeKind)
            {
                case "string":
                    sb.Append("            jw.WriteString(Encoding.UTF8.GetBytes(value.");
                    sb.Append(prop.Name);
                    sb.AppendLine("));");
                    break;
                case "int32":
                    sb.Append("            jw.WriteNumber(value.");
                    sb.Append(prop.Name);
                    sb.AppendLine(");");
                    break;
                case "int64":
                    sb.Append("            jw.WriteNumber(value.");
                    sb.Append(prop.Name);
                    sb.AppendLine(");");
                    break;
                case "float64":
                    sb.Append("            jw.WriteNumber(value.");
                    sb.Append(prop.Name);
                    sb.AppendLine(");");
                    break;
                case "boolean":
                    sb.Append("            jw.WriteBoolean(value.");
                    sb.Append(prop.Name);
                    sb.AppendLine(");");
                    break;
            }
        }

        sb.AppendLine("            jw.WriteEndObject();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendDeserializer(StringBuilder sb, TypeInfo type)
    {
        sb.Append("    file readonly struct ");
        sb.Append(type.Name);
        sb.Append("JsonDeserializer : IDeserializer<");
        sb.Append(type.Name);
        sb.AppendLine(">");
        sb.AppendLine("    {");
        sb.Append("        public ");
        sb.Append(type.Name);
        sb.AppendLine(" Deserialize(ReadOnlySpan<byte> data)");
        sb.AppendLine("        {");
        sb.AppendLine("            var reader = new JsonReader(data);");
        sb.Append("            var obj = new ");
        sb.Append(type.Name);
        sb.AppendLine("();");
        sb.AppendLine("            reader.Read();");
        sb.AppendLine(
            "            while (reader.Read() && reader.TokenType == TokenType.PropertyName)"
        );
        sb.AppendLine("            {");
        sb.AppendLine("                var p = reader.GetStringRaw();");
        sb.AppendLine("                reader.Read();");

        for (var i = 0; i < type.Properties.Length; i++)
        {
            var prop = type.Properties[i];
            var keyword = i == 0 ? "if" : "else if";
            var u8Name = $"\"{prop.JsonName}\"u8";

            sb.Append("                ");
            sb.Append(keyword);
            sb.Append(" (p.SequenceEqual(");
            sb.Append(u8Name);
            sb.AppendLine("))");

            switch (prop.TypeKind)
            {
                case "string":
                    sb.Append("                    obj.");
                    sb.Append(prop.Name);
                    sb.AppendLine(" = Encoding.UTF8.GetString(reader.GetStringRaw());");
                    break;
                case "int32":
                    sb.AppendLine("                {");
                    sb.AppendLine("                    reader.TryGetInt32(out var __v);");
                    sb.Append("                    obj.");
                    sb.Append(prop.Name);
                    sb.AppendLine(" = __v;");
                    sb.AppendLine("                }");
                    break;
                case "int64":
                    sb.AppendLine("                {");
                    sb.AppendLine("                    reader.TryGetInt64(out var __v);");
                    sb.Append("                    obj.");
                    sb.Append(prop.Name);
                    sb.AppendLine(" = __v;");
                    sb.AppendLine("                }");
                    break;
                case "float64":
                    sb.AppendLine("                {");
                    sb.AppendLine("                    reader.TryGetFloat64(out var __v);");
                    sb.Append("                    obj.");
                    sb.Append(prop.Name);
                    sb.AppendLine(" = __v;");
                    sb.AppendLine("                }");
                    break;
                case "boolean":
                    sb.AppendLine("                {");
                    sb.AppendLine("                    reader.TryGetBool(out var __v);");
                    sb.Append("                    obj.");
                    sb.Append(prop.Name);
                    sb.AppendLine(" = __v;");
                    sb.AppendLine("                }");
                    break;
            }
        }

        if (type.Properties.Length > 0)
        {
            sb.AppendLine("                else reader.TrySkip();");
        }
        else
        {
            sb.AppendLine("                reader.TrySkip();");
        }

        sb.AppendLine("            }");
        sb.AppendLine("            return obj;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendRegistration(StringBuilder sb, TypeInfo type)
    {
        var typeName = type.Name;
        var ns = type.Namespace;
        var typeRef = string.IsNullOrEmpty(ns) ? typeName : $"global::{ns}.{typeName}";

        sb.Append("file static class ");
        sb.Append(typeName);
        sb.AppendLine("SerDeRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.Append("        global::PicoJson.JsonSerializer._serializers[typeof(");
        sb.Append(typeRef);
        sb.Append(")] = new ");
        sb.Append(typeName);
        sb.AppendLine("JsonSerializer();");
        sb.Append("        global::PicoJson.JsonSerializer._deserializers[typeof(");
        sb.Append(typeRef);
        sb.Append(")] = new ");
        sb.Append(typeName);
        sb.AppendLine("JsonDeserializer();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    internal readonly record struct TypeInfo(
        string FullyQualifiedName,
        string Namespace,
        string Name,
        PropertyInfo[] Properties
    )
    {
        public bool Equals(TypeInfo other) =>
            FullyQualifiedName == other.FullyQualifiedName
            && Namespace == other.Namespace
            && Name == other.Name
            && Properties.AsSpan().SequenceEqual(other.Properties.AsSpan());

        public override int GetHashCode()
        {
            var hash = FullyQualifiedName.GetHashCode();
            hash = (hash * 397) ^ Namespace.GetHashCode();
            hash = (hash * 397) ^ Name.GetHashCode();
            foreach (var p in Properties)
                hash = (hash * 397) ^ p.GetHashCode();
            return hash;
        }
    }

    internal readonly record struct PropertyInfo(string Name, string JsonName, string TypeKind);
}
