Console.OutputEncoding = System.Text.Encoding.UTF8;

// ═══ 1. Rich Model ═══
Console.WriteLine("─── 1. Rich Model Round-trip ───");
var cfg = new TomlConfig
{
    Name = "MyApp",
    Version = "2.0.0",
    Port = 8080,
    Pi = 3.14,
    Price = 149.99m,
    CreatedAt = new DateTime(2024, 6, 15, 12, 0, 0, DateTimeKind.Utc),
    ReleaseDate = new DateOnly(2024, 6, 15),
    Id = Guid.Parse("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
    Tags = ["web", "api"],
    Secret = "hidden",
};
var bytes = TomlSerializer.SerializeToUtf8Bytes(cfg);
Console.WriteLine(Encoding.UTF8.GetString(bytes));
var rst = TomlSerializer.Deserialize<TomlConfig>(bytes);
Console.WriteLine($"  OK: {rst?.Name}, Secret: '{rst?.Secret}'");

// ═══ 2. Attributes ═══
Console.WriteLine("\n─── 2. Attributes ───");
Console.WriteLine("  [TomlCamelCase]:");
Console.WriteLine(
    Encoding.UTF8.GetString(
        TomlSerializer.SerializeToUtf8Bytes(new CamelToml { ProductName = "X", StockCount = 1 })
    )
);

Console.WriteLine("  [TomlKey]+[TomlIgnore]:");
Console.WriteLine(
    Encoding.UTF8.GetString(
        TomlSerializer.SerializeToUtf8Bytes(
            new AttrToml
            {
                AppName = "Demo",
                Secret = "x",
                Port = 99,
            }
        )
    )
);

Console.WriteLine("  [TomlDateTimeFormat]:");
Console.WriteLine(
    Encoding.UTF8.GetString(
        TomlSerializer.SerializeToUtf8Bytes(new DtToml { DueDate = new DateTime(2024, 12, 31) })
    )
);

Console.WriteLine("  [TomlConverter]:");
var cb = TomlSerializer.SerializeToUtf8Bytes(new ConvToml { Tag = new TomlTag { Value = "hi" } });
Console.WriteLine(Encoding.UTF8.GetString(cb));
var cr = TomlSerializer.Deserialize<ConvToml>(cb);
Console.WriteLine($"  Tag: {cr?.Tag.Value}");

// ═══ 3. Raw Reader ═══
Console.WriteLine("\n─── 3. Raw Reader ───");
var sample = "[server]\nhost = \"localhost\"\nport = 8080\n\nscores = [10, 20, 30]\n"u8;
var r = new TomlReader(sample);
while (r.Read())
    Console.WriteLine(
        $"  pos={r.BytesConsumed, 4}  depth={r.Depth}  {r.TokenType, -14}  k='{Encoding.UTF8.GetString(r.KeySpan)}' v='{Encoding.UTF8.GetString(r.ValueSpan)}'"
    );

// ═══ 4. Raw Writer + Arrays ═══
Console.WriteLine("\n─── 4. Raw Writer ───");
var buf = new ArrayBufferWriter<byte>(256);
var w = new TomlWriter(buf);
w.WriteComment("Generated by PicoToml");
w.WriteTable("server");
w.WriteKeyValue("host", "localhost");
w.WriteKeyValue("port", 8080);
w.WriteStartArray("ports"u8);
w.WriteArrayValue(80);
w.WriteArrayValue(443);
w.WriteEndArray();
Console.WriteLine(Encoding.UTF8.GetString(buf.WrittenSpan));

// ═══ 5. IBufferWriter overload ═══
Console.WriteLine("─── 5. Serialize<T>(IBufferWriter) ───");
var pb = new ArrayBufferWriter<byte>(64);
TomlSerializer.Serialize(pb, new TomlConfig { Name = "X" });
Console.WriteLine($"  Bytes: {pb.WrittenSpan.Length}");

// ═══ 6. File I/O — read from data file ═══
Console.WriteLine("\n─── 6. File I/O ───");
var dataDir = Path.Combine(AppContext.BaseDirectory, "data");
var dataFile = Path.Combine(dataDir, "config.toml");
var fileBytes = File.ReadAllBytes(dataFile);
var fromFile = TomlSerializer.Deserialize<TomlConfig>(fileBytes);
Console.WriteLine($"  Read {dataFile} ({fileBytes.Length} bytes)");
Console.WriteLine($"  Config: {fromFile?.Name} v{fromFile?.Version}");
Console.WriteLine($"  Tags: [{string.Join(", ", fromFile?.Tags ?? [])}]");

// Round-trip: serialize back and re-read
var roundBytes = TomlSerializer.SerializeToUtf8Bytes(fromFile!);
var reRead = TomlSerializer.Deserialize<TomlConfig>(roundBytes);
Console.WriteLine($"  Round-trip OK: {reRead?.Name == fromFile?.Name}");

// ═══ 7. NaN guard ═══
Console.WriteLine("\n─── 7. NaN Guard ───");
try
{
    new TomlWriter(new ArrayBufferWriter<byte>(64)).WriteKeyValue("v", double.NaN);
}
catch (ArgumentException ex)
{
    Console.WriteLine($"  {ex.Message}");
}

// ═══ 8. Inline Table ═══
Console.WriteLine("\n─── 8. Inline Table ───");
var ib = new ArrayBufferWriter<byte>(256);
var iw = new TomlWriter(ib);
iw.WriteComment("Inline table demo");
iw.WriteStartInlineTable("database");
iw.WriteKeyValue("host"u8, "localhost");
iw.WriteKeyValue("port"u8, 5432);
iw.WriteEndInlineTable();
Console.WriteLine(Encoding.UTF8.GetString(ib.WrittenSpan));

// ═══ 9. Array Table [[key]] ═══
Console.WriteLine("─── 9. Array Table ───");
var ab = new ArrayBufferWriter<byte>(256);
var aw = new TomlWriter(ab);
aw.WriteArrayTable("servers"u8);
aw.WriteKeyValue("host"u8, "srv1.example.com");
aw.WriteKeyValue("port"u8, 80);
aw.WriteBlankLine();
aw.WriteArrayTable("servers"u8);
aw.WriteKeyValue("host"u8, "srv2.example.com");
aw.WriteKeyValue("port"u8, 443);
Console.WriteLine(Encoding.UTF8.GetString(ab.WrittenSpan));

// ═══ 10. Multi-Line String Reader ═══
Console.WriteLine("─── 10. Multi-Line String ───");
var mlToml = "desc = \"\"\"\nHello,\nWorld!\n\"\"\"\n"u8;
var mr = new TomlReader(mlToml);
while (mr.Read())
    Console.WriteLine(
        $"  pos={mr.BytesConsumed, 4}  depth={mr.Depth}  {mr.TokenType, -14}  k='{Encoding.UTF8.GetString(mr.KeySpan)}' v='{Encoding.UTF8.GetString(mr.ValueSpan)}'"
    );

Console.WriteLine("\nAll samples passed.");

// ═══ Models ═══
public class TomlConfig
{
    public string Name { get; set; } = "";
    public string Version { get; set; } = "";
    public int Port { get; set; }
    public double Pi { get; set; }
    public decimal Price { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateOnly ReleaseDate { get; set; }
    public Guid Id { get; set; }
    public List<string> Tags { get; set; } = [];

    [TomlIgnore]
    public string Secret { get; set; } = "";
}

[TomlCamelCase]
public class CamelToml
{
    public string ProductName { get; set; } = "";
    public int StockCount { get; set; }
}

public class AttrToml
{
    [TomlKey("app_name")]
    public string AppName { get; set; } = "";

    [TomlIgnore]
    public string Secret { get; set; } = "";

    [TomlKey("listen_port")]
    public int Port { get; set; }
}

public class DtToml
{
    [TomlDateTimeFormat("yyyy-MM-dd")]
    public DateTime DueDate { get; set; }
}

public class TomlTag
{
    public string Value { get; set; } = "";
}

public class TagCvt : ITomlConverter<TomlTag>
{
    public void Write(IBufferWriter<byte> w, TomlTag v)
    {
        w.Write(Encoding.UTF8.GetBytes($"[{v.Value}]"));
    }

    public TomlTag Read(ref TomlReader r)
    {
        return new TomlTag { Value = Encoding.UTF8.GetString(r.ValueSpan).Trim('[', ']') };
    }
}

public class ConvToml
{
    [TomlConverter(typeof(TagCvt))]
    public TomlTag Tag { get; set; } = new();
}
