using PicoToml;

// ═══ Rich Sample: TOML serialization ═══
var config = new AppConfig
{
    Title = "MyApp",
    Version = 2,
    Debug = true,
    Port = 8080,
    Host = "localhost",
    Pi = 3.14,
    MaxConnections = 10_000L
};

// Serialize
var bytes = TomlSerializer.SerializeToUtf8Bytes(config);
Console.WriteLine("=== Serialized TOML ===");
Console.WriteLine(Encoding.UTF8.GetString(bytes));

// Deserialize
var restored = TomlSerializer.Deserialize<AppConfig>(bytes);
Console.WriteLine($"\n=== Round-trip ===");
Console.WriteLine($"  Title:          {restored?.Title}");
Console.WriteLine($"  Version:        {restored?.Version}");
Console.WriteLine($"  Debug:          {restored?.Debug}");
Console.WriteLine($"  Port:           {restored?.Port}");
Console.WriteLine($"  Host:           {restored?.Host}");
Console.WriteLine($"  Pi:             {restored?.Pi}");
Console.WriteLine($"  MaxConnections: {restored?.MaxConnections}");
Console.WriteLine(
    $"  OK: {restored?.Title == config.Title && restored?.Version == config.Version}"
);

// ═══ Low-level Reader demo ═══
Console.WriteLine("\n=== Reader token stream ===");
var raw =
    "[server]\nhost = \"localhost\"\nport = 8080\n\n[[users]]\nname = \"alice\"\n\n[[users]]\nname = \"bob\"\n"u8;
var r = new TomlReader(raw);
while (r.Read())
{
    if (r.TokenType == PicoSerDe.Abs.TokenType.ObjectStart)
        Console.WriteLine(
            $"  [{Encoding.UTF8.GetString(r.TablePath)}]" + (r.IsArrayTable ? " (array)" : "")
        );
    else if (r.TokenType == PicoSerDe.Abs.TokenType.ArrayStart)
        Console.WriteLine($"  [[{Encoding.UTF8.GetString(r.TablePath)}]] (array)");
    else
        Console.WriteLine(
            $"  {Encoding.UTF8.GetString(r.KeySpan)} = {Encoding.UTF8.GetString(r.ValueSpan)}"
        );
}

// ═══ Writer demo ═══
Console.WriteLine("\n=== Writer output ===");
var buf = new ArrayBufferWriter<byte>(256);
var w2 = new TomlWriter(buf);
w2.WriteComment("Generated by PicoToml");
w2.WriteKeyValue("app", "demo");
w2.WriteBlankLine();
w2.WriteTable("database");
w2.WriteKeyValue("host", "localhost");
w2.WriteKeyValue("port", 5432);
Console.WriteLine(Encoding.UTF8.GetString(buf.WrittenSpan));

public class AppConfig
{
    public string Title { get; set; } = "";
    public int Version { get; set; }
    public bool Debug { get; set; }
    public int Port { get; set; }
    public string Host { get; set; } = "";
    public double Pi { get; set; }
    public long MaxConnections { get; set; }
}
