namespace PicoMsgPack.Gen;

[Generator(LanguageNames.CSharp)]
public sealed class MsgPackSerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var providers = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (n, _) => IsCandidate(n),
                transform: static (ctx, _) => Transform(ctx)
            )
            .Where(static t => t.HasValue)
            .Select(static (t, _) => t!.Value);

        context.RegisterSourceOutput(providers.Collect(), static (spc, types) => GenerateAll(spc, types));
    }

    private static bool IsCandidate(SyntaxNode node)
    {
        if (node is not InvocationExpressionSyntax { Expression: var e }) return false;
        var name = e switch
        {
            MemberAccessExpressionSyntax { Name: var n } => n,
            MemberBindingExpressionSyntax { Name: var n } => n,
            _ => null,
        };
        return name switch
        {
            GenericNameSyntax gn => gn.Identifier.Text,
            SimpleNameSyntax sn => sn.Identifier.Text,
            _ => null,
        } is "Serialize" or "SerializeToUtf8Bytes" or "Deserialize";
    }

    private static TypeInfo? Transform(GeneratorSyntaxContext ctx)
    {
        if (ctx.SemanticModel.GetSymbolInfo(ctx.Node).Symbol is not IMethodSymbol m) return null;
        if (m.ContainingType.Name != "MsgPackSerializer" || m.ContainingType.ContainingNamespace?.ToDisplayString() != "PicoMsgPack")
            return null;
        if (m.TypeArguments.Length != 1) return null;

        var t = m.TypeArguments[0];
        if (t.SpecialType != SpecialType.None) return null;
        if (t is not INamedTypeSymbol nt) return null;

        var ns = nt.ContainingNamespace?.ToDisplayString() ?? "";
        if (ns == "<global namespace>") ns = "";

        var props = new List<PropInfo>();
        int autoKey = 0;

        foreach (var member in nt.GetMembers())
        {
            if (member is not IPropertySymbol p) continue;
            if (p.DeclaredAccessibility != Accessibility.Public) continue;
            if (p.IsStatic || p.IsIndexer) continue;
            if (p.IsReadOnly && p.SetMethod is null) continue;
            if (p.GetMethod is null) continue;
            if (HasAttr(p, "MsgPackIgnoreAttribute")) continue;

            var (kind, nullable, _) = TypeKindResolver.Resolve(p.Type);
            if (kind is null) continue;

            int key = GetKey(p) ?? autoKey++;

            string? elemKind = null, elemName = null;
            if (kind is "list" or "array")
            {
                ITypeSymbol? et = p.Type switch { IArrayTypeSymbol a => a.ElementType, INamedTypeSymbol n2 => n2.TypeArguments[0], _ => null };
                if (et is not null) { var (ek, _, _) = TypeKindResolver.Resolve(et); if (ek is not null) { elemKind = ek; elemName = TypeKindResolver.MapTypeName(ek, et); } }
            }

            props.Add(new PropInfo(p.Name, key, kind, p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), nullable, elemKind, elemName));
        }

        return new TypeInfo(nt.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), ns, nt.Name, props.ToImmutableArray());
    }

    private static int? GetKey(IPropertySymbol p)
    {
        foreach (var a in p.GetAttributes())
            if (a.AttributeClass?.Name == "MsgPackKeyAttribute" && a.ConstructorArguments.Length == 1 && a.ConstructorArguments[0].Value is int k)
                return k;
        return null;
    }

    private static bool HasAttr(IPropertySymbol p, string name)
    {
        foreach (var a in p.GetAttributes())
            if (a.AttributeClass?.Name == name) return true;
        return false;
    }

    private static void GenerateAll(SourceProductionContext spc, ImmutableArray<TypeInfo> types)
    {
        var seen = new HashSet<string>();
        foreach (var t in types)
        {
            if (!seen.Add(t.FullyQualifiedName)) continue;
            spc.AddSource($"{t.Name}_MsgPackSerializer.g.cs", SourceText.From(Gen(t), Encoding.UTF8));
        }
    }

    private static string Gen(TypeInfo type)
    {
        var s = new StringBuilder();
        s.AppendLine("// <auto-generated/>");
        s.AppendLine("using System; using System.Buffers; using System.Text; using System.Runtime.CompilerServices;");
        s.AppendLine("using PicoSerDe.Abs; using PicoMsgPack;");
        if (!string.IsNullOrEmpty(type.Namespace)) { s.Append("using "); s.Append(type.Namespace); s.AppendLine(";"); }
        s.AppendLine();

        // Sort by key for deterministic output
        var sorted = type.Properties.OrderBy(p => p.Key).ToImmutableArray();

        // Serializer
        s.Append("file readonly struct "); s.Append(type.Name); s.Append("MsgPackSerializer : ISerializer<"); s.Append(type.Name); s.AppendLine("> {");
        s.Append("    public void Serialize(IBufferWriter<byte> writer, "); s.Append(type.Name); s.AppendLine(" value) {");
        s.Append("        var mw = new MsgPackWriter(writer);\n        mw.WriteStartObject("); s.Append(sorted.Length); s.AppendLine(");");
        foreach (var p in sorted)
        {
            s.Append("        mw.WriteInt32("); s.Append(p.Key); s.AppendLine(");");
            WriteValue(s, p, $"value.{p.Name}");
        }
        s.AppendLine("        mw.WriteEndObject();");
        s.AppendLine("    } }");
        s.AppendLine();

        // Deserializer
        s.Append("file readonly struct "); s.Append(type.Name); s.Append("MsgPackDeserializer : IDeserializer<"); s.Append(type.Name); s.AppendLine("> {");
        s.Append("    public "); s.Append(type.Name); s.AppendLine(" Deserialize(ReadOnlySpan<byte> data) {");
        s.AppendLine("        var reader = new MsgPackReader(data);");
        s.Append("        var obj = new "); s.Append(type.Name); s.AppendLine("();");
        s.AppendLine("        reader.Read(); // ObjectStart");
        s.AppendLine("        while (reader.Read() && reader.TokenType != TokenType.ObjectEnd) {");
        s.AppendLine("            reader.TryGetInt32(out var __key);");
        s.AppendLine("            reader.Read(); // value");
        s.AppendLine("            switch (__key) {");
        foreach (var p in sorted)
        {
            s.Append("                case "); s.Append(p.Key); s.AppendLine(":");
            ReadValue(s, p, "obj");
            s.AppendLine("                    break;");
        }
        s.AppendLine("                default: reader.TrySkip(); break;");
        s.AppendLine("            }");
        s.AppendLine("        }");
        s.AppendLine("        return obj;");
        s.AppendLine("    } }");
        s.AppendLine();

        // Registration
        s.Append("file static class "); s.Append(type.Name); s.AppendLine("__Reg {");
        s.AppendLine("    [ModuleInitializer] internal static void Register() {");
        s.Append("        MsgPackSerializer.Register<"); s.Append(type.Name); s.Append(">(new "); s.Append(type.Name);
        s.Append("MsgPackSerializer(), new "); s.Append(type.Name); s.AppendLine("MsgPackDeserializer()); } }");
        return s.ToString();
    }

    private static void WriteValue(StringBuilder s, PropInfo p, string acc)
    {
        switch (p.TypeKind)
        {
            case "string": s.Append("mw.WriteString(Encoding.UTF8.GetBytes("); s.Append(acc); s.AppendLine("));"); break;
            case "int32": s.Append("mw.WriteInt32("); s.Append(acc); s.AppendLine(");"); break;
            case "int64": s.Append("mw.WriteInt64("); s.Append(acc); s.AppendLine(");"); break;
            case "float64": s.Append("mw.WriteFloat64("); s.Append(acc); s.AppendLine(");"); break;
            case "boolean": s.Append("mw.WriteBoolean("); s.Append(acc); s.AppendLine(");"); break;
            case "datetime": s.Append("mw.WriteString(Encoding.UTF8.GetBytes("); s.Append(acc); s.AppendLine(".ToString(\"O\")));"); break;
            case "guid": case "enum": s.Append("mw.WriteString(Encoding.UTF8.GetBytes("); s.Append(acc); s.AppendLine(".ToString()));"); break;
            case "list": case "array":
                s.Append("mw.WriteStartArray("); s.Append(acc); s.AppendLine(".Count);");
                s.Append("        for (int __i = 0; __i < "); s.Append(acc); s.AppendLine(".Count; __i++) {");
                WriteElem(s, p, $"{acc}[__i]");
                s.AppendLine("        }");
                break;
            default: s.Append("mw.WriteString(Encoding.UTF8.GetBytes("); s.Append(acc); s.AppendLine(".ToString()));"); break;
        }
    }

    private static void WriteElem(StringBuilder s, PropInfo p, string acc)
    {
        switch (p.ElementTypeKind)
        {
            case "string": s.Append("        mw.WriteString(Encoding.UTF8.GetBytes("); s.Append(acc); s.AppendLine("));"); break;
            case "int32": s.Append("        mw.WriteInt32("); s.Append(acc); s.AppendLine(");"); break;
            default: s.Append("        mw.WriteString(Encoding.UTF8.GetBytes("); s.Append(acc); s.AppendLine(".ToString()));"); break;
        }
    }

    private static void ReadValue(StringBuilder s, PropInfo p, string target)
    {
        switch (p.TypeKind)
        {
            case "string":
                s.Append("                    "); s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = Encoding.UTF8.GetString(reader.GetStringRaw());"); break;
            case "int32":
                s.Append("                    reader.TryGetInt32(out var __v); "); s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = __v;"); break;
            case "int64":
                s.Append("                    reader.TryGetInt64(out var __v); "); s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = __v;"); break;
            case "float64":
                s.Append("                    reader.TryGetFloat64(out var __v); "); s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = __v;"); break;
            case "boolean":
                s.Append("                    reader.TryGetBool(out var __v); "); s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = __v;"); break;
            case "datetime":
                s.Append("                    DateTime.TryParse(Encoding.UTF8.GetString(reader.GetStringRaw()), out var __dt); ");
                s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = __dt;"); break;
            case "guid":
                s.Append("                    Guid.TryParse(reader.GetStringRaw(), out var __g); ");
                s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = __g;"); break;
            case "enum":
                s.Append("                    Enum.TryParse<"); s.Append(p.TypeFullName); s.Append(">(Encoding.UTF8.GetString(reader.GetStringRaw()), out var __e); ");
                s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(" = __e;"); break;
            case "list": case "array":
                s.Append("                    if (reader.TokenType == TokenType.ArrayStart) { while (reader.Read() && reader.TokenType != TokenType.ArrayEnd) { ");
                ReadElem(s, p, target);
                s.Append(" } }"); s.AppendLine();
                break;
        }
    }

    private static void ReadElem(StringBuilder s, PropInfo p, string target)
    {
        switch (p.ElementTypeKind)
        {
            case "string": s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(".Add(Encoding.UTF8.GetString(reader.GetStringRaw())); "); break;
            case "int32": s.Append("int __ev; reader.TryGetInt32(out __ev); "); s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(".Add(__ev); "); break;
            default: s.Append(target); s.Append("."); s.Append(p.Name); s.AppendLine(".Add(default); "); break;
        }
    }
}

internal readonly record struct TypeInfo(string FullyQualifiedName, string Namespace, string Name, ImmutableArray<PropInfo> Properties);
internal readonly record struct PropInfo(string Name, int Key, string TypeKind, string TypeFullName, bool IsNullable, string? ElementTypeKind, string? ElementTypeName);
