namespace PicoMsgPack.Gen;

using PropertyInfo = PicoSerDe.Gen.PropertyInfo;
using TypeInfo = PicoSerDe.Gen.TypeInfo;

[Generator(LanguageNames.CSharp)]
public sealed class MsgPackSerializerGenerator : IIncrementalGenerator
{
    private static readonly PicoSerDe.Gen.FormatConfig Config = new(
        "MsgPackSerializer",
        "PicoMsgPack",
        "msgpack"
    );

    private static readonly PicoSerDe.Gen.AttributeHelpers Attrs = new(
        _ => false,
        _ => null,
        HasMsgPackIgnore,
        GetMsgPackConverter,
        _ => null,
        GetIntKey: GetMsgPackKey,
        OverrideKindWithStringOnConverter: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeProviders = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: static (n, _) => IsCandidate(n),
                transform: static (ctx, _) => Transform(ctx)
            )
            .Where(static t => t is not null)
            .Select(static (t, _) => t!.Value);

        context.RegisterSourceOutput(
            typeProviders.Collect(),
            static (spc, types) => GenerateAll(spc, types)
        );
    }

    static bool IsCandidate(SyntaxNode n) => PicoSerDe.Gen.GenInfrastructure.IsCandidate(n);

    static TypeInfo? Transform(GeneratorSyntaxContext ctx)
    {
        var info = PicoSerDe.Gen.GenInfrastructure.TransformType(ctx, Config, Attrs);
        if (info is not { } ti)
            return info;

        // Check for [MsgPackExtensionTag] on properties and override type kind
        if (
            ctx.SemanticModel.GetSymbolInfo(ctx.Node).Symbol is not IMethodSymbol method
            || method.TypeArguments.Length != 1
            || method.TypeArguments[0] is not INamedTypeSymbol namedType
        )
            return ti;

        var props = ti.Properties;
        var builder = ImmutableArray.CreateBuilder<PropertyInfo>();
        bool changed = false;
        foreach (var p in props)
        {
            var member = namedType.GetMembers(p.Name).FirstOrDefault();
            if (member is IPropertySymbol ps)
            {
                var extTag = GetMsgPackExtensionTag(ps);
                if (extTag.HasValue)
                {
                    builder.Add(p with { TypeKind = "extension", ExtensionTag = extTag });
                    changed = true;
                    continue;
                }
            }
            builder.Add(p);
        }
        return changed ? ti with { Properties = builder.ToImmutable() } : ti;
    }

    // ── Attribute helpers ──

    static bool HasMsgPackIgnore(IPropertySymbol p)
    {
        foreach (var a in p.GetAttributes())
            if (a.AttributeClass?.Name == "MsgPackIgnoreAttribute")
                return true;
        return false;
    }

    static string? GetMsgPackConverter(IPropertySymbol p)
    {
        foreach (var a in p.GetAttributes())
            if (
                a.AttributeClass?.Name == "MsgPackConverterAttribute"
                && a.ConstructorArguments.Length >= 1
                && a.ConstructorArguments[0].Value is INamedTypeSymbol ct
            )
                return ct.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return null;
    }

    static byte? GetMsgPackExtensionTag(IPropertySymbol p)
    {
        foreach (var a in p.GetAttributes())
            if (
                a.AttributeClass?.Name == "MsgPackExtensionTagAttribute"
                && a.ConstructorArguments.Length == 1
                && a.ConstructorArguments[0].Value is byte tag
            )
                return tag;
        return null;
    }

    static int? GetMsgPackKey(IPropertySymbol p)
    {
        foreach (var a in p.GetAttributes())
            if (
                a.AttributeClass?.Name == "MsgPackKeyAttribute"
                && a.ConstructorArguments.Length == 1
                && a.ConstructorArguments[0].Value is int k
            )
                return k;
        return null;
    }

    // ── Source generation ──

    static void GenerateAll(SourceProductionContext spc, ImmutableArray<TypeInfo> types)
    {
        var seen = new HashSet<string>();
        foreach (var t in types)
        {
            if (!seen.Add(t.FullyQualifiedName))
                continue;
            spc.AddSource(
                $"{t.Name}_MsgPackSerializer.g.cs",
                SourceText.From(Gen(t), Encoding.UTF8)
            );
        }
    }

    static string Gen(TypeInfo type)
    {
        int c = 0;
        var s = new StringBuilder();
        s.AppendLine("// <auto-generated/>");
        s.AppendLine(
            "using System; using System.Buffers; using System.Text; using System.Runtime.CompilerServices;"
        );
        s.AppendLine("using System.Collections.Generic; using PicoSerDe.Core; using PicoMsgPack;");
        if (!string.IsNullOrEmpty(type.Namespace))
        {
            s.Append("using ");
            s.Append(type.Namespace);
            s.AppendLine(";");
        }
        s.AppendLine();

        var sorted = type.Properties.OrderBy(p => p.IntKey ?? 0).ToImmutableArray();

        s.Append("file readonly struct ");
        s.Append(type.Name);
        s.Append("MsgPackSerializer : ISerializer<");
        s.Append(type.Name);
        s.AppendLine("> {");
        s.Append("    public void Serialize(IBufferWriter<byte> writer, ");
        s.Append(type.Name);
        s.AppendLine(" value) {");
        s.Append("        var mw = new MsgPackWriter(writer); mw.WriteStartObject(");
        s.Append(sorted.Length);
        s.AppendLine(");");
        foreach (var p in sorted)
        {
            s.Append("        mw.WriteInt32(");
            s.Append(p.IntKey ?? 0);
            s.AppendLine(");");
            WriteSer(s, p, $"value.{p.Name}", "        ", ref c);
        }
        s.AppendLine("        mw.WriteEndObject(); } }");
        s.AppendLine();

        s.Append("file readonly struct ");
        s.Append(type.Name);
        s.Append("MsgPackDeserializer : IDeserializer<");
        s.Append(type.Name);
        s.AppendLine("> {");
        s.Append("    public ");
        s.Append(type.Name);
        s.AppendLine(" Deserialize(ReadOnlySpan<byte> data) {");
        s.AppendLine("        var reader = new MsgPackReader(data); var obj = new ");
        s.Append(type.Name);
        s.AppendLine("();");
        s.AppendLine(
            "        reader.Read(); while (reader.Read() && reader.TokenType != TokenType.ObjectEnd) {"
        );
        s.AppendLine("            reader.TryGetInt32(out var __k); reader.Read(); switch (__k) {");
        foreach (var p in sorted)
        {
            s.Append("                case ");
            s.Append(p.IntKey ?? 0);
            s.AppendLine(":");
            WriteDeser(s, p, "obj", "                ", ref c);
            s.AppendLine("                    break;");
        }
        s.AppendLine("                default: reader.TrySkip(); break; } }");
        s.AppendLine("        return obj; } }");
        s.AppendLine();

        s.Append("file static class ");
        s.Append(type.Name);
        s.AppendLine("__Reg {");
        s.AppendLine("    [ModuleInitializer] internal static void Register() {");
        s.Append("        MsgPackSerializer.Register<");
        s.Append(type.Name);
        s.Append(">(new ");
        s.Append(type.Name);
        s.Append("MsgPackSerializer(), new ");
        s.Append(type.Name);
        s.AppendLine("MsgPackDeserializer()); } }");
        return s.ToString();
    }

    static void WriteSer(StringBuilder s, PropertyInfo p, string a, string ind, ref int c)
    {
        if (p.ConverterTypeFullName is not null)
        {
            s.Append(ind);
            s.Append("var __cnv");
            s.Append(c);
            s.Append(" = new ");
            s.Append(p.ConverterTypeFullName);
            s.AppendLine("();");
            s.Append(ind);
            s.Append("var __bw");
            s.Append(c);
            s.Append(" = new ArrayBufferWriter<byte>();");
            s.AppendLine();
            s.Append(ind);
            s.Append("__cnv");
            s.Append(c);
            s.Append(".Write(__bw");
            s.Append(c);
            s.Append(", ");
            s.Append(a);
            s.AppendLine(");");
            s.Append(ind);
            s.Append("mw.WriteString(__bw");
            s.Append(c);
            s.Append(".WrittenSpan);");
            s.AppendLine();
            c++;
            return;
        }
        bool needsNullCheck = p.TypeKind == "string" || p.IsNullableReference;
        if (p.IsNullable && !p.IsNullableReference)
        {
            s.Append(ind);
            s.Append("if (");
            s.Append(a);
            s.AppendLine(".HasValue) {");
            ind += "    ";
            a += ".Value";
        }
        else if (needsNullCheck)
        {
            s.Append(ind);
            s.Append("if (");
            s.Append(a);
            s.AppendLine(" != null) {");
            ind += "    ";
        }
        switch (p.TypeKind)
        {
            case "string":
                s.Append(ind);
                s.Append("mw.WriteString(Encoding.UTF8.GetBytes(");
                s.Append(a);
                s.AppendLine("));");
                break;
            case "int32":
                s.Append(ind);
                s.Append("mw.WriteInt32(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "int64":
                s.Append(ind);
                s.Append("mw.WriteInt64(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "float32":
                s.Append(ind);
                s.Append("mw.WriteFloat64((double)(");
                s.Append(a);
                s.AppendLine("));");
                break;
            case "float64":
                s.Append(ind);
                s.Append("mw.WriteFloat64(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "boolean":
                s.Append(ind);
                s.Append("mw.WriteBoolean(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "datetime":
                s.Append(ind);
                s.Append("mw.WriteString(Encoding.UTF8.GetBytes(");
                s.Append(a);
                s.AppendLine(".ToString(\"O\")));");
                break;
            case "timespan":
                s.Append(ind);
                s.Append("mw.WriteString(Encoding.UTF8.GetBytes(");
                s.Append(a);
                s.AppendLine(".ToString()));");
                break;
            case "dateonly":
            case "timeonly":
            case "guid":
            case "enum":
                s.Append(ind);
                s.Append("mw.WriteString(Encoding.UTF8.GetBytes(");
                s.Append(a);
                s.AppendLine(".ToString()));");
                break;
            case "list":
            case "array":
                s.Append(ind);
                s.Append("mw.WriteStartArray(");
                s.Append(p.TypeKind == "array" ? $"{a}.Length" : $"{a}.Count");
                s.AppendLine(");");
                s.Append(ind);
                s.Append("foreach (var __i in ");
                s.Append(a);
                s.AppendLine(") {");
                WriteSerElem(s, p, "__i", ind + "    ", ref c);
                s.Append(ind);
                s.AppendLine("}");
                s.Append(ind);
                s.AppendLine("mw.WriteEndArray();");
                break;
            case "bytes":
                s.Append(ind);
                s.Append("mw.WriteBytes(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "extension":
                s.Append(ind);
                s.Append("mw.WriteExtension(");
                s.Append(p.ExtensionTag ?? 0);
                s.Append(", ");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "dict":
                s.Append(ind);
                s.Append("mw.WriteStartObject(");
                s.Append(a);
                s.AppendLine(".Count);");
                s.Append(ind);
                s.Append("foreach (var __kv in ");
                s.Append(a);
                s.AppendLine(") {");
                s.Append(ind);
                s.Append("    mw.WriteString(Encoding.UTF8.GetBytes(__kv.Key));");
                WriteSerElem(s, p, "__kv.Value", ind + "    ", ref c);
                s.Append(ind);
                s.AppendLine("}");
                s.Append(ind);
                s.AppendLine("mw.WriteEndObject();");
                break;
            case "object":
                if (p.NestedProperties.Length == 0)
                {
                    s.Append(ind);
                    s.AppendLine("mw.WriteNull();");
                    break;
                }
                s.Append(ind);
                s.Append("if (");
                s.Append(a);
                s.AppendLine(" == null) mw.WriteNull(); else {");
                var ns = p.NestedProperties.OrderBy(n => n.IntKey ?? 0).ToImmutableArray();
                s.Append(ind);
                s.Append("    mw.WriteStartObject(");
                s.Append(ns.Length);
                s.AppendLine(");");
                foreach (var n in ns)
                {
                    s.Append(ind);
                    s.Append("    mw.WriteInt32(");
                    s.Append(n.IntKey ?? 0);
                    s.AppendLine(");");
                    WriteSer(s, n, $"{a}.{n.Name}", ind + "    ", ref c);
                }
                s.Append(ind);
                s.AppendLine("    mw.WriteEndObject(); }");
                break;
            default:
                s.Append(ind);
                s.Append("mw.WriteString(Encoding.UTF8.GetBytes(");
                s.Append(a);
                s.AppendLine(".ToString()));");
                break;
        }
        if (p.IsNullable || p.TypeKind == "string")
        {
            ind = ind.Substring(4);
            s.Append(ind);
            s.AppendLine("} else mw.WriteNull();");
        }
    }

    static void WriteSerElem(StringBuilder s, PropertyInfo p, string a, string ind, ref int c)
    {
        switch (p.ElementTypeKind)
        {
            case "string":
                s.Append(ind);
                s.Append("mw.WriteString(Encoding.UTF8.GetBytes(");
                s.Append(a);
                s.AppendLine("));");
                break;
            case "int32":
                s.Append(ind);
                s.Append("mw.WriteInt32(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "int64":
                s.Append(ind);
                s.Append("mw.WriteInt64(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "float32":
                s.Append(ind);
                s.Append("mw.WriteFloat64((double)(");
                s.Append(a);
                s.AppendLine("));");
                break;
            case "float64":
                s.Append(ind);
                s.Append("mw.WriteFloat64(");
                s.Append(a);
                s.AppendLine(");");
                break;
            case "boolean":
                s.Append(ind);
                s.Append("mw.WriteBoolean(");
                s.Append(a);
                s.AppendLine(");");
                break;
            default:
                s.Append(ind);
                s.Append("mw.WriteString(Encoding.UTF8.GetBytes(");
                s.Append(a);
                s.AppendLine(".ToString()));");
                break;
        }
    }

    static void WriteDeser(StringBuilder s, PropertyInfo p, string target, string ind, ref int c)
    {
        var t = $"{target}.{p.Name}";
        if (p.ConverterTypeFullName is not null)
        {
            s.Append(ind);
            s.Append("var __cnv");
            s.Append(c);
            s.Append(" = new ");
            s.Append(p.ConverterTypeFullName);
            s.AppendLine("();");
            s.Append(ind);
            s.Append(t);
            s.Append(" = __cnv");
            s.Append(c++);
            s.AppendLine(".Read(ref reader);");
            return;
        }
        switch (p.TypeKind)
        {
            case "string":
                s.Append(ind);
                s.Append("if (reader.TokenType == TokenType.Null) ");
                s.Append(t);
                s.AppendLine(" = null; else ");
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = Encoding.UTF8.GetString(reader.GetStringRaw());");
                break;
            case "int32":
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("if (reader.TokenType == TokenType.Null) { int? __nv = null; ");
                    s.Append(ind);
                    s.Append(t);
                    s.AppendLine(" = __nv; } else {");
                }
                s.Append(ind);
                s.Append("reader.TryGetInt32(out var __v");
                s.Append(c);
                s.AppendLine(");");
                s.Append(ind);
                s.Append(t);
                s.Append(" = __v");
                s.Append(c++);
                s.AppendLine(";");
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("}");
                }
                break;
            case "int64":
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("if (reader.TokenType == TokenType.Null) { long? __nv = null; ");
                    s.Append(ind);
                    s.Append(t);
                    s.AppendLine(" = __nv; } else {");
                }
                s.Append(ind);
                s.Append("reader.TryGetInt64(out var __v");
                s.Append(c);
                s.AppendLine(");");
                s.Append(ind);
                s.Append(t);
                s.Append(" = __v");
                s.Append(c++);
                s.AppendLine(";");
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("}");
                }
                break;
            case "float64":
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("if (reader.TokenType == TokenType.Null) { double? __nv = null; ");
                    s.Append(ind);
                    s.Append(t);
                    s.AppendLine(" = __nv; } else {");
                }
                s.Append(ind);
                s.Append("reader.TryGetFloat64(out var __v");
                s.Append(c);
                s.AppendLine(");");
                s.Append(ind);
                s.Append(t);
                s.Append(" = __v");
                s.Append(c++);
                s.AppendLine(";");
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("}");
                }
                break;
            case "boolean":
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("if (reader.TokenType == TokenType.Null) { bool? __nv = null; ");
                    s.Append(ind);
                    s.Append(t);
                    s.AppendLine(" = __nv; } else {");
                }
                s.Append(ind);
                s.Append("reader.TryGetBool(out var __v");
                s.Append(c);
                s.AppendLine(");");
                s.Append(ind);
                s.Append(t);
                s.Append(" = __v");
                s.Append(c++);
                s.AppendLine(";");
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.AppendLine("}");
                }
                break;
            case "datetime":
                s.Append(ind);
                s.AppendLine(
                    "var __dtRaw = Encoding.UTF8.GetString(reader.GetStringRaw()); DateTime.TryParse(__dtRaw, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.RoundtripKind, out var __dt);"
                );
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = __dt;");
                break;
            case "timespan":
                s.Append(ind);
                s.AppendLine(
                    "TimeSpan.TryParse(Encoding.UTF8.GetString(reader.GetStringRaw()), out var __ts);"
                );
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = __ts;");
                break;
            case "dateonly":
                s.Append(ind);
                s.AppendLine(
                    "var __doRaw = Encoding.UTF8.GetString(reader.GetStringRaw()); DateOnly.TryParse(__doRaw, out var __dov);"
                );
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = __dov;");
                break;
            case "timeonly":
                s.Append(ind);
                s.AppendLine(
                    "var __toRaw = Encoding.UTF8.GetString(reader.GetStringRaw()); TimeOnly.TryParse(__toRaw, out var __tov);"
                );
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = __tov;");
                break;
            case "guid":
                s.Append(ind);
                s.AppendLine("Guid.TryParse(reader.GetStringRaw(), out var __g);");
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = __g;");
                break;
            case "enum":
                s.Append(ind);
                s.Append("Enum.TryParse<");
                s.Append(p.TypeFullName);
                s.AppendLine(">(Encoding.UTF8.GetString(reader.GetStringRaw()), out var __e);");
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = __e;");
                break;
            case "bytes":
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = reader.GetStringRaw().ToArray();");
                break;
            case "extension":
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = reader.GetStringRaw().ToArray();");
                break;
            case "list":
                s.Append(ind);
                s.Append(t);
                s.Append(" ??= new List<");
                s.Append(p.ElementTypeName);
                s.AppendLine(">(16);");
                s.Append(ind);
                s.AppendLine("if (reader.TokenType == TokenType.ArrayStart) {");
                s.Append(ind);
                s.AppendLine(
                    "    while (reader.Read() && reader.TokenType != TokenType.ArrayEnd) {"
                );
                ReadDeserElem(s, p, t, ".Add", ind + "        ", ref c);
                s.Append(ind);
                s.AppendLine("    } }");
                break;
            case "array":
                s.Append(ind);
                s.Append("var __l = new List<");
                s.Append(p.ElementTypeName);
                s.AppendLine(">(16);");
                s.Append(ind);
                s.AppendLine("if (reader.TokenType == TokenType.ArrayStart) {");
                s.Append(ind);
                s.AppendLine(
                    "    while (reader.Read() && reader.TokenType != TokenType.ArrayEnd) {"
                );
                ReadDeserElem(s, p, "__l", ".Add", ind + "        ", ref c);
                s.Append(ind);
                s.AppendLine("    } }");
                s.Append(ind);
                s.Append(t);
                s.AppendLine(" = __l.ToArray();");
                break;
            case "dict":
                s.Append(ind);
                s.Append(t);
                s.Append(" ??= new Dictionary<string, ");
                s.Append(p.ElementTypeName);
                s.AppendLine(">(16);");
                s.Append(ind);
                s.AppendLine("if (reader.TokenType == TokenType.ObjectStart) {");
                s.Append(ind);
                s.AppendLine(
                    "    while (reader.Read() && reader.TokenType == TokenType.PropertyName) {"
                );
                s.Append(ind);
                s.AppendLine(
                    "        var __dk = Encoding.UTF8.GetString(reader.GetStringRaw()); reader.Read();"
                );
                ReadDeserElem(s, p, $"{t}[__dk]", " =", ind + "        ", ref c);
                s.Append(ind);
                s.AppendLine("    } }");
                break;
            case "object":
                if (p.NestedProperties.Length == 0)
                {
                    s.Append(ind);
                    s.Append(t);
                    s.AppendLine(" = default!;");
                    break;
                }
                s.Append(ind);
                s.AppendLine("if (reader.TokenType == TokenType.Null) {");
                if (p.IsNullable)
                {
                    s.Append(ind);
                    s.Append("    ");
                    s.Append(t);
                    s.AppendLine(" = null;");
                }
                s.Append(ind);
                s.AppendLine("} else {");
                s.Append(ind);
                s.Append("    var __o = new ");
                s.Append(p.TypeFullName);
                s.AppendLine("();");
                s.Append(ind);
                s.AppendLine(
                    "    while (reader.Read() && reader.TokenType != TokenType.ObjectEnd) {"
                );
                s.Append(ind);
                s.AppendLine(
                    "        reader.TryGetInt32(out var __nk); reader.Read(); switch (__nk) {"
                );
                var ns = p.NestedProperties.OrderBy(n => n.IntKey ?? 0).ToImmutableArray();
                foreach (var n in ns)
                {
                    s.Append(ind);
                    s.Append("            case ");
                    s.Append(n.IntKey ?? 0);
                    s.AppendLine(":");
                    WriteDeser(s, n, "__o", ind + "                ", ref c);
                    s.Append(ind);
                    s.AppendLine("                break;");
                }
                s.Append(ind);
                s.AppendLine("            default: reader.TrySkip(); break; } }");
                s.Append(ind);
                s.Append("    ");
                s.Append(t);
                s.AppendLine(" = __o; }");
                break;
        }
    }

    static void ReadDeserElem(
        StringBuilder s,
        PropertyInfo p,
        string target,
        string op,
        string ind,
        ref int c
    )
    {
        switch (p.ElementTypeKind)
        {
            case "string":
                s.Append(ind);
                s.Append(target);
                s.Append(op);
                s.AppendLine("(Encoding.UTF8.GetString(reader.GetStringRaw()));");
                break;
            case "int32":
                s.Append(ind);
                s.AppendLine("reader.TryGetInt32(out var __ev);");
                s.Append(ind);
                s.Append(target);
                s.Append(op);
                s.AppendLine("(__ev);");
                break;
            case "int64":
                s.Append(ind);
                s.AppendLine("reader.TryGetInt64(out var __ev);");
                s.Append(ind);
                s.Append(target);
                s.Append(op);
                s.AppendLine("(__ev);");
                break;
            case "float64":
                s.Append(ind);
                s.AppendLine("reader.TryGetFloat64(out var __ev);");
                s.Append(ind);
                s.Append(target);
                s.Append(op);
                s.AppendLine("(__ev);");
                break;
            case "boolean":
                s.Append(ind);
                s.AppendLine("reader.TryGetBool(out var __ev);");
                s.Append(ind);
                s.Append(target);
                s.Append(op);
                s.AppendLine("(__ev);");
                break;
            default:
                s.Append(ind);
                s.Append(target);
                s.Append(op);
                s.AppendLine("(default!);");
                break;
        }
    }
}
